### PR TITLE
remove tracker

### PR DESCRIPTION
**Pull request by stevemar**
this reverts #23 and #24

### CODE REVIEW

**Review by scottdangelo — APPROVED** [review]
Code looks good. CI is failing.
Is there something on the publishing side that needs changing (i.e. the use of metric-tracker image in the button?)

**Comment by scottdangelo** [comment]
100 16341  100    67  100 16274     51  12435  0:00:01  0:00:01 --:--:-- 12432
+resp='{"error":"Maximum workspaces limit exceeded. Limit = 5","code":400}'
+json
+echo '{"error":"Maximum' workspaces limit exceeded. Limit = '5","code":400}'
{
  "error": "Maximum workspaces limit exceeded. Limit = 5",
  "code": 400
}

**Comment by stevemar** [comment]
@Tomcli can you take a look at this PR? 

@scottdangelo the travis tests haven't passed in a while, i should probably disable them and look into it.

**Review by Tomcli — APPROVED** [review]
LGTM, I think the travis CI account has too many namespaces, maybe you need to clean up on that.

**Pull request merged**
